fix: setup and use intersphinx mappings
mozilla-releng/relengdocs pull request #241
Opened 2023-09-15 14:33 UTC by ahal

We have the intersphinx extension enabled, but never set up the external targets. This will allow us to more easily link to our other documentation pages.

2023-09-15 21:31 UTC, gbrownmozilla requested changes
I checked the first 1/2 of the changes (against https://moz-releng-docs--241.org.readthedocs.build/en/241/...) and all the links were good. Then I checked a few of the last ones and found some problems; not sure about the links in the middle.

2023-09-15 21:31 UTC, gbrownmozilla commented on how-to/taskcluster/testing_relpro.rst
> +``rebuild_kinds`` refers to a task :external+firefox:doc:`kind <taskcluster/kinds.html>` that we want to make sure we rebuild. We use this in the `promote_firefox_partner_repack <https://hg.mozilla.o
The `kind` link doesn't seem to work?

2023-09-15 21:31 UTC, gbrownmozilla commented on how-to/taskcluster/testing_relpro.rst
> +currently :external+firefox:doc:`here <taskcluster/actions>`.
This link doesn't seem to work.

2023-09-25 13:58 UTC, ahal commented
Thanks, I resolved the issues. One was a mistake, the other was broken prior to this patch (I pointed it at the Taskgraph docs instead which is what I'm pretty sure it used to be pointing at).

I noticed both issues links were generating warnings, and I don't see any other warnings anywhere else, so I think all those middle links are fine as well.

2023-09-25 14:07 UTC, gbrownmozilla approved these changes
Thanks!

2023-09-25 15:41 UTC, merged